#!/usr/bin/env bash
#
# Creates the "Gridstream Service Desk" Airtable base with the Service Tickets
# table used by the /support intake system and n8n workflows.
#
# Prerequisites:
#   1. An Airtable Personal Access Token from https://airtable.com/create/tokens
#      with scopes:  schema.bases:write  +  data.records:write
#      and access granted to the target workspace.
#   2. Your workspace ID (starts with "wsp") — visible in the URL when viewing
#      the workspace at airtable.com, e.g. https://airtable.com/workspaces/wspXXXXXXXXXXXXXX
#
# Usage:
#   AIRTABLE_TOKEN=pat... AIRTABLE_WORKSPACE_ID=wsp... ./scripts/create-airtable-base.sh
#
# Notes:
#   - "SLA Due" is a plain dateTime field: the n8n intake workflow computes it
#     (submitted + 4h for Major/Emergency, + 24h for Minor/Routine) so no
#     Airtable formula is needed.
#   - The Airtable API cannot create views. After running, add two grid views
#     by hand: "Open Tickets" (Status is none of Resolved, Closed) and
#     "By Report Month" (grouped by Report Month) for the monthly VA reports.

set -euo pipefail

: "${AIRTABLE_TOKEN:?Set AIRTABLE_TOKEN to a personal access token (pat...)}"
: "${AIRTABLE_WORKSPACE_ID:?Set AIRTABLE_WORKSPACE_ID to your workspace id (wsp...)}"

DATETIME_OPTS='{
  "timeZone": "America/Chicago",
  "dateFormat": { "name": "us", "format": "M/D/YYYY" },
  "timeFormat": { "name": "12hour", "format": "h:mma" }
}'

echo "Creating base 'Gridstream Service Desk'..."

RESPONSE=$(curl -sS -X POST "https://api.airtable.com/v0/meta/bases" \
  -H "Authorization: Bearer ${AIRTABLE_TOKEN}" \
  -H "Content-Type: application/json" \
  -d @- <<EOF
{
  "name": "Gridstream Service Desk",
  "workspaceId": "${AIRTABLE_WORKSPACE_ID}",
  "tables": [
    {
      "name": "Service Tickets",
      "description": "Service requests from gridstream.ai/support — ICVAHCS chiller maintenance contract 36C26326Q0707",
      "fields": [
        { "name": "Ticket ID", "type": "singleLineText",
          "description": "GS-YYYYMMDD-XXXXXX, generated by the website form; key for status lookup" },
        { "name": "Submitted At", "type": "dateTime", "options": ${DATETIME_OPTS} },
        { "name": "Status", "type": "singleSelect", "options": { "choices": [
          { "name": "New",          "color": "redBright" },
          { "name": "Acknowledged", "color": "orangeBright" },
          { "name": "Dispatched",   "color": "yellowBright" },
          { "name": "Tech On Site", "color": "blueBright" },
          { "name": "Resolved",     "color": "greenBright" },
          { "name": "Closed",       "color": "grayBright" }
        ] } },
        { "name": "Urgency", "type": "singleSelect", "options": { "choices": [
          { "name": "Minor / Routine",   "color": "tealBright" },
          { "name": "Major / Emergency", "color": "redBright" }
        ] } },
        { "name": "Equipment", "type": "singleSelect", "options": { "choices": [
          { "name": "Chiller 1 — York YMC2-S3517AB (SN SLGM427590)", "color": "blueBright" },
          { "name": "Chiller 2 — York YMC2-S3517AB (SN SLGM427610)", "color": "cyanBright" },
          { "name": "Chiller 3 — Trane CVHF1070 (SN L09B06301)",     "color": "purpleBright" },
          { "name": "Cooling Tower / Condenser Water System",        "color": "tealBright" },
          { "name": "Multiple Units",                                "color": "orangeBright" },
          { "name": "Other / Not Sure",                              "color": "grayBright" }
        ] } },
        { "name": "Requester Name",  "type": "singleLineText" },
        { "name": "Requester Role", "type": "singleSelect", "options": { "choices": [
          { "name": "Contracting Officer’s Representative (COR)", "color": "blueBright" },
          { "name": "Boiler Plant Operator",                      "color": "cyanBright" },
          { "name": "HVAC Technician",                            "color": "tealBright" },
          { "name": "Facilities Management",                      "color": "greenBright" },
          { "name": "Contracting Officer",                        "color": "purpleBright" },
          { "name": "Other VA Staff",                             "color": "grayBright" }
        ] } },
        { "name": "Requester Email", "type": "email" },
        { "name": "Requester Phone", "type": "phoneNumber" },
        { "name": "Location Detail", "type": "singleLineText" },
        { "name": "Description", "type": "multilineText" },
        { "name": "Best Callback Time", "type": "singleLineText" },
        { "name": "SLA Due", "type": "dateTime", "options": ${DATETIME_OPTS},
          "description": "Set by n8n: Submitted + 4h (Major/Emergency) or + 24h (Minor/Routine)" },
        { "name": "Acknowledged At", "type": "dateTime", "options": ${DATETIME_OPTS},
          "description": "Set when Gridstream acknowledges; the emergency escalation loop re-alerts until this is filled" },
        { "name": "JCI Notified At", "type": "dateTime", "options": ${DATETIME_OPTS} },
        { "name": "Dispatched At",   "type": "dateTime", "options": ${DATETIME_OPTS} },
        { "name": "On Site At",      "type": "dateTime", "options": ${DATETIME_OPTS} },
        { "name": "Resolved At",     "type": "dateTime", "options": ${DATETIME_OPTS} },
        { "name": "Public Notes", "type": "multilineText",
          "description": "Shown to the requester on the /support/status page — keep customer-safe" },
        { "name": "Internal Notes", "type": "multilineText" },
        { "name": "Resolution Notes", "type": "multilineText",
          "description": "Feeds the monthly maintenance/inspection report to the VA POC" },
        { "name": "Report Month", "type": "singleLineText",
          "description": "YYYY-MM, set by n8n; group by this for the monthly VA report" }
      ]
    }
  ]
}
EOF
)

BASE_ID=$(echo "$RESPONSE" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("id",""))')

if [ -z "$BASE_ID" ]; then
  echo "❌ Base creation failed. API response:"
  echo "$RESPONSE" | python3 -m json.tool
  exit 1
fi

TABLE_ID=$(echo "$RESPONSE" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d["tables"][0]["id"])')

echo "✅ Base created:  $BASE_ID"
echo "✅ Table created: $TABLE_ID (Service Tickets)"
echo

echo "Seeding a sample ticket so you can test n8n field mapping..."
SEED=$(curl -sS -X POST "https://api.airtable.com/v0/${BASE_ID}/Service%20Tickets" \
  -H "Authorization: Bearer ${AIRTABLE_TOKEN}" \
  -H "Content-Type: application/json" \
  -d '{
    "records": [{ "fields": {
      "Ticket ID": "GS-00000000-SAMPLE",
      "Submitted At": "2026-07-16T14:00:00.000Z",
      "Status": "New",
      "Urgency": "Minor / Routine",
      "Equipment": "Chiller 3 — Trane CVHF1070 (SN L09B06301)",
      "Requester Name": "Sample Requester",
      "Requester Role": "Boiler Plant Operator",
      "Requester Email": "sample@example.com",
      "Requester Phone": "(555) 555-5555",
      "Description": "Sample ticket created by setup script — safe to delete.",
      "SLA Due": "2026-07-17T14:00:00.000Z",
      "Report Month": "2026-07"
    } }]
  }')

if echo "$SEED" | grep -q '"id"'; then
  echo "✅ Sample ticket seeded (delete it whenever you like)."
else
  echo "⚠️  Sample ticket could not be created (base itself is fine). Response:"
  echo "$SEED" | python3 -m json.tool
fi

echo
echo "Done. Next steps:"
echo "  1. Open the base and add views: 'Open Tickets' (Status ≠ Resolved/Closed)"
echo "     and 'By Report Month' (grouped by Report Month)."
echo "  2. Use Base ID ${BASE_ID} in your n8n Airtable nodes."
